### ISSUE TITLE
Bad merge commit

### ISSUE THREAD

**Issue by jurecuhalev** [PrinceCornNM/ember-multi-step#1]
This commit `https://github.com/PrinceCornNM/ember-multi-step/commit/db0a6cb3fd3a07463b0ab6e1035dd99272818fd0` contains conflicting information. `ember s` fails when trying to run it inside the addon folder

**Comment by conradlz** [comment]
Thanks for the heads up I should be able to clean that up tonight.

**Comment by conradlz** [comment]
Fixed with https://github.com/PrinceCornNM/ember-multi-step/commit/2674eb7406677f3f0258434904cc397dae0e1343
